name: Build and Deploy Jekyll Site

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout
      uses: actions/checkout@v3
     
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: false
       
    - name: Install dependencies
      run: |
        bundle config unset deployment
        bundle install
     
    - name: Build site
      run: bundle exec jekyll build
      
    - name: List generated files
      run: ls -la _site/
      
    - name: Print deployment info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Repository owner: ${{ github.repository_owner }}"
        echo "Repository name: ${{ github.event.repository.name }}"
        echo "Your site will be available at:"
        echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo "Alternative URL (if different):"
        echo "https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"
     
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true
        
    - name: Print final deployment message
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "🚀 Deployment complete!"
        echo "Your site should be live at:"
        echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo "Note: It may take a few minutes for changes to appear."
